# global settings
safe: true
encoding: "utf-8"

# serve settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chriszhong.github.io" # the base hostname & protocol for your site

# build settings
markdown: kramdown
highlighter: Pygments
exclude:
  - img/avatar.png
  - img/graduation-hat.svg
  - img/k-state.svg
  - img/me.jpg

# site settings
title: Christopher Zhong | Software Engineer | Bio &amp; Portfolio
email: chriszhong@users.noreply.github.com
description: > # this means to ignore newlines until the next "<key>:"
  Christopher Zhong is a Software Engineer and has a PhD in Computer Science.
  See Christopher's Bio, Resume, and more.
  Get in touch with Christopher Zhong.
analytics:
  id: UA-664111-4
github:
  username: ChrisZhong
linkedin:
  username: ChrisZhong
google_plus:
  username: ChristopherZhong
